# safelist
branches:
    only:
        - /.*/

services:
    - docker

deploy:
    github_token: $GITHUB_TOKEN

matrix:
    fast_finish: true
    include:
        -   language: python
            python: 3.6
            dist: xenial
            before_cache:
            cache:
            before_install:
            name: "security scan"
            script: |
                bash .ci/ci_check_commit.sh

        -   language: java
            jdk: openjdk8
            os: linux
            dist: xenial
            sudo: required
            name: "2 groups"
            script: |
                bash .ci/ci_check.sh && bash .ci/ci_cross_groups_demo_check.sh

        -   language: java
            jdk: openjdk11
            os: linux
            dist: xenial
            sudo: required
            name: "normal & gm"
            script: |
                bash .ci/ci_check.sh && bash .ci/ci_cross_gm_demo_check.sh

        -   language: java
            jdk: openjdk11
            os: linux
            dist: xenial
            sudo: required
            name: "bcos2.0 & fabric1.4"
            script: |
                bash .ci/ci_check.sh && bash .ci/ci_demo_check.sh

        #-   language: java
        #    jdk: openjdk11
        #    os: linux
        #    dist: xenial
        #    sudo: required
        #    name: "performance test"
        #    script: |
        #        bash .ci/ci_performance_test.sh

        #-   language: java
        #    jdk: openjdk14
        #    os: linux
        #    dist: xenial
        #    sudo: required
        #    script: |
        #        bash .ci/ci_check.sh && bash .ci/ci_demo_check.sh

        #-   language: java
        #    jdk: openjdk11
        #    os: osx # docker is not supported on mac os
        #    before_install:
        #        - brew install gradle && gradle wrapper

before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
    directories:
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/
before_install:
    - gradle wrapper
script: |
    bash .ci/ci_check.sh && bash .ci/ci_demo_check.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)
