[verifiers]
    [verifiers.payment.bcos-group1]
        chainType = 'BCOS2.0'
        pubKey = [
            '...'
        ]
    [verifiers.payment.bcos-group2]
        chainType = 'BCOS2.0'
        pubKey = [
            '...'
        ]
    [verifiers.payment.bcos-gm]
        chainType = 'GM_BCOS2.0'
        pubKey = [
            '...'
        ]
    [verifiers.payment.fabric-mychannel]
        chainType = 'Fabric1.4'
        [verifiers.payment.fabric-mychannel.endorserCA]
            Org1MSP = 'classpath:verifiers/org1CA/ca.org1.example.com-cert.pem'
            Org2MSP = 'classpath:verifiers/org2CA/ca.org2.example.com-cert.pem'
        [verifiers.payment.fabric-mychannel.ordererCA]
            OrdererMSP = 'classpath:verifiers/ordererCA/ca.example.com-cert.pem'