[common]
    network = 'network'
    visible = true

[stubs]
    path = 'classpath:stubs'

[rpc] # rpc ip & port
    address = '0.0.0.0'
    port = 8250
    caCert = 'classpath:ca.crt'
    sslCert = 'classpath:ssl.crt'
    sslKey = 'classpath:ssl.key'

[p2p]
    listenIP = '0.0.0.0'
    listenPort = 25500
    caCert = 'classpath:ca.crt'
    sslCert = 'classpath:ssl.crt'
    sslKey = 'classpath:ssl.key'
    peers = ["127.0.0.1:25501"]