[common]
    network = 'payment'
    visible = true

[stubs]
    path = 'classpath:stubs'

[server] # rpc ip & port
    address = '127.0.0.1'
    port = 8250
    keyStoreType = 'PKCS12'
    keyStore = 'classpath:server.keystore'
    keyStorePass = '123456'
    trustStore = 'classpath:server.truststore'
    trustStorePass = '123456'

[p2p]
    listenIP = '0.0.0.0'
    listenPort = 25500
    caCert = 'classpath:p2p/ca.crt'
    sslCert = 'classpath:p2p/node.crt'
    sslKey = 'classpath:p2p/node.key'
    peers = ['127.0.0.1:25501','127.0.0.1:25502']

[[htlc]]
    selfPath = 'payment.bcos.htlc'
    selfAccount = 'default_bcos'
    counterpartyPath = 'payment.fabric.htlc'
    counterpartyAccount = 'default_fabric'