[common]
    stub = 'bcos1' # stub must be same with directory name
    type = 'BCOS'

[smCrypto]
    # boolean
    enable = false

[account]
    accountFile = 'classpath:/stubs/bcos1/0xa1ca07c7ff567183c889e1ad5f4dcd37716831ca.pem'

[channelService]
    timeout = 60000  # millisecond
    caCert = 'classpath:/stubs/bcos1/ca.crt'
    sslCert = 'classpath:/stubs/bcos1/sdk.crt'
    sslKey = 'classpath:/stubs/bcos1/sdk.key'
    groupId = 1
    connectionsStr = ['127.0.0.1:20200']

# resources is a list
[[resources]]
    # name cannot be repeated
    name = 'HelloWorldContract'
    type = 'BCOS_CONTRACT'
    contractAddress = '0x8827cca7f0f38b861b62dae6d711efe92a1e3602'
[[resources]]
    name = 'FirstTomlContract'
    type = 'BCOS_CONTRACT'
    contractAddress = '0x8827cca7f0f38b861b62dae6d711efe92a1e3602'
