[common]
    stub = 'bcos2' # stub must be same with directory name
    type = 'BCOS'

[guomi]
    # boolean
    open = true

[account]
    accountFile = '0xa1ca07c7ff567183c889e1ad5f4dcd37716831ca.p12'
    password = '123456'

[channelService]
    timeout = 60000  # millisecond
    caCert = 'classpath:/stubs/bcos2/ca.crt'
    sslCert = 'classpath:/stubs/bcos2/sdk.crt'
    sslKey = 'classpath:/stubs/bcos2/sdk.key'
    groupId = 1
    connectionsStr = ['127.0.0.1:20200']

# resources is a list
[[resources]]
    # name cannot be repeated
    name = 'HelloWorldContract'
    type = 'BCOS_CONTRACT'
    contractAddress = '0x38735ad749aebd9d6e9c7350ae00c28c8903dc7a'
[[resources]]
    name = 'HelloTomlContract'
    type = 'BCOS_CONTRACT'
    contractAddress = '0x38735ad749aebd9d6e9c7350ae00c28c8903dc7a'
