[common]
    stub = 'fabric'
    type = 'Fabric1.4'

[fabricServices]
    channelName = 'mychannel'
    orgName = 'Org1'
    mspId = 'Org1MSP'
    orgUserName = 'fabric'
    orgUserAccountPath = 'classpath:accounts/fabric'
    ordererTlsCaFile = 'classpath:/stubs/fabric/ordererTlsCaFile'
    ordererAddress = 'grpcs://localhost:7050'

[peers]
    [peers.org1]
        peerTlsCaFile = 'classpath:/stubs/fabric/peerOrg1CertFile'
        peerAddress = 'grpcs://localhost:7051'
    [peers.org2]
         peerTlsCaFile = 'classpath:/stubs/fabric/peerOrg2CertFile'
         peerAddress = 'grpcs://localhost:9051'

# resources is a list
[[resources]]
    # name cannot be repeated
    name = 'htlc'
    type = 'FABRIC_CONTRACT'
    chainCodeName = 'htlcSample'
    chainLanguage = "go"
    peers=['org1']
[[resources]]
    # name cannot be repeated
    name = 'ledger'
    type = 'FABRIC_CONTRACT'
    chainCodeName = 'ledgerSample'
    chainLanguage = "go"
    peers=['org1']
