# WeCross
WECROSS_VERSION=v1.3.0
# WeCross Console
WECROSS_CONSOLE_VERSION=v1.3.0
# WeCross Account Manager
WECROSS_ACCOUNT_MANAGER_VERSION=v1.3.0
# WeCross BCOS2.0 Stub
WECROSS_BCOS2_STUB_VERSION=v1.3.0
# WeCross BCOS3.0 Stub
WECROSS_BCOS3_STUB_VERSION=v1.3.0
# WeCross Fabric1.4 Stub
WECROSS_FABRIC1_STUB_VERSION=v1.3.0
# WeCross Fabric2.0 Stub
WECROSS_FABRIC2_STUB_VERSION=v1.3.0
# WeCross Java SDK
WECROSS_JAVA_SDK_VERSION=v1.3.0

# FISCO BCOS
BCOS_VERSION=v2.9.1
# FISCO BCOS 3.0
BCOS3_VERSION=v3.2.0
# FISCO BCOS Console
BCOS3_CONSOLE_VERSION=v3.2.0

GIT_URL_BASE='github.com'
GITHUB_PROXY=''
