# WeCross
WECROSS_VERSION=release-1.3.0
# WeCross Console
WECROSS_CONSOLE_VERSION=release-1.3.0
# WeCross Account Manager
WECROSS_ACCOUNT_MANAGER_VERSION=release-1.3.0
# WeCross BCOS2.0 Stub
WECROSS_BCOS2_STUB_VERSION=release-1.3.0
# WeCross Fabric1.4 Stub
WECROSS_FABRIC1_STUB_VERSION=release-1.3.0
# WeCross Fabric2.0 Stub
WECROSS_FABRIC2_STUB_VERSION=release-1.3.0
# WeCross Java SDK
WECROSS_JAVA_SDK_VERSION=release-1.3.0

# FISCO BCOS
BCOS_VERSION=v2.9.1
# FISCO BCOS 3.0
BCOS3_VERSION=v3.2.0
# FISCO BCOS Console
BCOS3_CONSOLE_VERSION=release-3.2.0

WECROSS_CODE_SOURCE='github.com/WebankBlockchain'
GIT_URL_BASE='github.com'
GITHUB_PROXY=''
