# WeCross
WECROSS_VERSION=v1.0.1
# WeCross Console
WECROSS_CONSOLE_VERSION=v1.0.1
# WeCross Account Manager
WECROSS_ACCOUNT_MANAGER_VERSION=v1.0.1
# WeCross BCOS2.0 Stub
WECROSS_BCOS2_STUB_VERSION=v1.0.1
# WeCross Fabric1.4 Stub
WECROSS_FABRIC1_STUB_VERSION=v1.0.1
# WeCross Fabric2.0 Stub
WECROSS_FABRIC2_STUB_VERSION=v2.0.0
# WeCross Java SDK
WECROSS_JAVA_SDK_VERSION=v1.0.1

# FISCO BCOS
BCOS_VERSION=v2.7.1
# FISCO BCOS Console
BCOS_CONSOLE_VERSION=v1.0.10
