# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: actions check

on: [push, pull_request]

jobs:
  unittest:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: run ci_check.sh
        run: bash .ci/ci_check.sh
      - name: upload coverage
        run: bash <(curl -s https://codecov.io/bash)

  bcos-fabric:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: '123456'
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y mysql-client git curl libssl-dev default-jdk build-essential
      - name: run ci_demo_check.sh
        # The script only use ${1} as branch name. if GITHUB_BASE_REF is blank use GITHUB_REF
        run: bash .ci/ci_demo_check.sh ${GITHUB_BASE_REF} ${GITHUB_REF#refs/heads/}
        env:
          CI_DB_PASSWORD : '123456'

  normal-gm:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: '123456'
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y mysql-client git curl libssl-dev default-jdk build-essential
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql -u root --password=123456 -h 127.0.0.1 -P 3306 -e 'status;'
          mysql --host 127.0.0.1 --port 3306 -uroot -p123456 -e "SHOW DATABASES"

      - name: run ci_cross_gm_demo_check.sh
        # The script only use ${1} as branch name. if GITHUB_BASE_REF is blank use GITHUB_REF
        run: bash .ci/ci_cross_gm_demo_check.sh ${GITHUB_BASE_REF} ${GITHUB_REF#refs/heads/}
        env:
          CI_DB_PASSWORD : '123456'

  groups-groups:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: '123456'
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y mysql-client git curl libssl-dev default-jdk build-essential
      - name: run ci_cross_groups_demo_check.sh
        # The script only use ${1} as branch name. if GITHUB_BASE_REF is blank use GITHUB_REF
        run: bash .ci/ci_cross_groups_demo_check.sh ${GITHUB_BASE_REF} ${GITHUB_REF#refs/heads/}
        env:
          CI_DB_PASSWORD : '123456'