name: normal-gm

on: [pull_request]

jobs:
  normal-gm:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'
      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql root password: '123456'
      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y mysql-client git curl libssl-dev build-essential
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql -u root --password=123456 -h 127.0.0.1 -P 3306 -e 'status;'
          mysql --host 127.0.0.1 --port 3306 -uroot -p123456 -e "SHOW DATABASES"
      - name: Set up JDK 1.8.0.382
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8.0.382'
      - name: run ci_cross_gm_demo_check.sh
        # The script only use ${1} as branch name. if GITHUB_BASE_REF is blank use GITHUB_REF
        run: java -version && bash -x .ci/ci_cross_gm_demo_check.sh ${GITHUB_BASE_REF} ${GITHUB_REF#refs/heads/}
        env:
          CI_DB_PASSWORD : '123456'
