name: mac_group-group

on: [pull_request]

jobs:
  mac_group-group:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'
      - name: mac prepare
        run: bash -x .ci/ci_mac_prepare.sh
        env:
          CI_DB_PASSWORD: '123456'
      - name: Set up JDK 1.8.0.382
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8.0.382'
      - name: run ci_cross_groups_demo_check.sh
        # The script only use ${1} as branch name. if GITHUB_BASE_REF is blank use GITHUB_REF
        run: java -version && bash -x .ci/ci_cross_groups_demo_check.sh ${GITHUB_BASE_REF} ${GITHUB_REF#refs/heads/}
        env:
          CI_DB_PASSWORD : '123456'