name: mac_normal-gm

on: [pull_request]

jobs:
  mac_normal-gm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '10'
      - name: mac prepare
        run: bash -x .ci/ci_mac_prepare.sh
        env:
          CI_DB_PASSWORD: '123456'
      - name: Verify MySQL connection from host
        run: |
          mysql -u root --password=123456 -h 127.0.0.1 -P 3306 -e 'status;'
          mysql --host 127.0.0.1 --port 3306 -uroot -p123456 -e "SHOW DATABASES"

      - name: run ci_cross_gm_demo_check.sh
        # The script only use ${1} as branch name. if GITHUB_BASE_REF is blank use GITHUB_REF
        run: bash .ci/ci_cross_gm_demo_check.sh ${GITHUB_BASE_REF} ${GITHUB_REF#refs/heads/}
        env:
          CI_DB_PASSWORD : '123456'
